### STAGE 2: Setup ###

FROM nginx:alpine

## Copy our default nginx config
COPY nginx/default.conf /etc/nginx/conf.d/
ADD .certificate/* /etc/ssl/

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY /dist /usr/share/nginx/html

# label
LABEL author="Edouard Topin"
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
