version: "3"
services:
  smartsearch-api:
    container_name: smartsearch-api
    deploy:
      replicas: 2
    image: "spacelama/api-go:dev"
    depends_on:
      - smartsearch-db
    ports:
      - "9000:9000"
    networks:
      - middleware
      - backend
  smartsearch-db:
    image: "mongo:latest"
    container_name: smartsearch-db
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/configdb:/data/configdb"
      - "./mongo/db:/data/db"
    networks:
      - backend
  smartsearch-web:
    container_name: smartsearch-web
    image: "spacelama/web:dev"
    deploy:
      replicas: 2
    depends_on:
      - smartsearch-api
    ports:
      - 443:443
      - 80:80
    networks:
      - frontend
      - middleware
  smartsearch-blog:
    container_name: smartsearch-blog
    image: "ghost:latest"
    ports:
      - 2368:2368
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
  middleware:
    driver: bridge
  backend:
    driver: bridge
