apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: smartsearch-api
  name: smartsearch-api
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: smartsearch-api
    spec:
      containers:
      - image: spacelama/api-go:dev
        name: smartsearch-api
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
