apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: smartsearch-db
  name: smartsearch-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: smartsearch-db
    spec:
      containers:
      - image: mongo:latest
        name: smartsearch-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/configdb
          name: smartsearch-db-claim0
        - mountPath: /data/db
          name: smartsearch-db-claim1
      restartPolicy: Always
      volumes:
      - name: smartsearch-db-claim0
        persistentVolumeClaim:
          claimName: smartsearch-db-claim0
      - name: smartsearch-db-claim1
        persistentVolumeClaim:
          claimName: smartsearch-db-claim1
status: {}
